name: AdventureAutoClub
favicon: null
layout_spectrum: 0.7257220635656267
typography_spectrum: 0.7232885910198092
title: Adventure Auto Club- where vehicles come out to play.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9715970647521317
  lightness: 0.9330570001620799
  saturation: 0.058435313403606415
  rhythmicContrast: 0.6757387998513877
purpose: []
